branches:
  except:
    - master
language: python
python:
  - "3.4"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.13.2-1-amd64.deb
install:
  - pip install -r requirements.txt
script:
  - python pyblog generate
