branches:
  except:
    - master
language: python
python:
  - "3.4"
  - "3.5"
matrix:
  allow_failures:
    - python: "nightly"
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install -y cmake
  # install pandoc
  - wget https://github.com/jgm/pandoc/releases/download/1.13.2/pandoc-1.13.2-1-amd64.deb
  - sudo dpkg -i pandoc-1.13.2-1-amd64.deb
  # install tidy-html5
  - git clone https://github.com/htacg/tidy-html5.git
  - cd tidy-html5/build/cmake
  - cmake ../..
  - make
  - sudo make install
  - cd ../../..
install:
  - pip install -r requirements.txt
script:
  - python pyblog generate
  - find build -path 'build/google*.html' -o -name '*.html' -print0 | xargs -0 tidy -q -e --gnu-emacs yes
